max_steps = 10
seq_len = 2048

[deployment]
type = "single_node"
num_infer_gpus = 1
num_train_gpus = 1

[ckpt]

[model]
name = "Qwen/Qwen3-0.6B"

[trainer.optim]
lr = 1e-5

[orchestrator]
batch_size = 128
rollouts_per_example = 8

[orchestrator.train.sampling]
max_completion_tokens = 1024

[[orchestrator.train.env]]
id = "primeintellect/alphabet-sort"
name = "alphabet-sort"
args = { min_turns = 2, max_turns = 2, min_names_per_turn = 1, max_names_per_turn = 3, similarity_power = 4, power_per_turn = false }

[inference]
