"""Generate self-contained per-(debater x judge x schedule) debate run configs.

Source of truth = the fragments + the spec below. Generated files under
generated/ are BUILD ARTIFACTS — never hand-edit them; edit a fragment or this
spec and re-run:  uv run python configs/debate/gen.py

Layout:
  base.toml             shared run+protocol invariants (tables only)
  debaters/<name>.toml  the trained policy: [model], [trainer.model] (lora),
                        [deployment], [inference], [orchestrator.train.sampling]
  judges/<name>.toml    [orchestrator.multi_agent.fixed.judge] (winner -> reward)
  grader-deepseek.txt   the ONE GT-correctness grader (deepseek), injected everywhere
  generated/            emitted, launch-ready configs (committed)

Launch:  uv run rl @ configs/debate/generated/<debater>__<judge>__<schedule>.toml
"""

import pathlib
import tomllib

HERE = pathlib.Path(__file__).parent
BASE = (HERE / "base.toml").read_text().rstrip()
GRADER = (HERE / "grader-deepseek.txt").read_text().strip()  # the ONE grader, verbatim
GRADER_ARGS = tomllib.loads(f"args = {GRADER}")["args"]
DEBATE_GRADER_KEYS = ("judge_base_url", "judge_model", "judge_api_key_var")

DEBATERS = {p.stem: p.read_text().rstrip() for p in sorted((HERE / "debaters").glob("*.toml"))}
JUDGES = {p.stem: p.read_text().rstrip() for p in sorted((HERE / "judges").glob("*.toml"))}

# Per-schedule: protocol (prompts_ref + schedule). Debate-eval group_size is a
# single shared constant (8) so twc is computed on a comparable resolvable subset
# across every schedule — see metric-comparability fix (commit 0f7b4924c).
EVAL_GROUP_SIZE = 8
SEQ4 = '[{ slot_id = 0, agents = ["debater_a"], phase = "propose" }, { slot_id = 1, agents = ["debater_b"], phase = "propose" }, { slot_id = 2, agents = ["debater_a"], phase = "critique" }, { slot_id = 3, agents = ["debater_b"], phase = "critique" }, { slot_id = 4, agents = ["judge"], phase = "final" }]'
PCD4 = '[{ slot_id = 0, agents = ["debater_a"], phase = "propose" }, { slot_id = 1, agents = ["debater_b"], phase = "critique" }, { slot_id = 2, agents = ["debater_a"], phase = "rebuttal" }, { slot_id = 3, agents = ["debater_b"], phase = "counter_proposal" }, { slot_id = 4, agents = ["judge"], phase = "final" }]'
PCD4F = '[{ slot_id = 0, agents = ["debater_a"], phase = "propose" }, { slot_id = 1, agents = ["debater_b"], phase = "critique" }, { slot_id = 2, agents = ["debater_a"], phase = "rebuttal" }, { slot_id = 3, agents = ["debater_b"], phase = "counter_critique" }, { slot_id = 4, agents = ["debater_a", "debater_b"], phase = "final" }, { slot_id = 5, agents = ["judge"], phase = "final" }]'
SCHEDULES = {
    "simul": dict(pref="selfplay_oe", sched=None),
    "sequential4": dict(pref="selfplay_oe_sequential4", sched=SEQ4),
    "pcd4": dict(pref="selfplay_oe_pcd4", sched=PCD4),
    "pcd4final": dict(pref="selfplay_oe_pcd4_final", sched=PCD4F),
}

PROJECT_DIR = "/lus/lfs1aip2/projects/a6r/joanv.a6r/work/prime-rl-main"
WANDB_PROJECT = "gpqa-openended-debate-calibration"
out = HERE / "generated"
out.mkdir(exist_ok=True)


def debate_args(pref, sched):
    sk = f", schedule = {sched}" if sched else ""
    gt_grader = "".join(f', {key} = "{GRADER_ARGS[key]}"' for key in DEBATE_GRADER_KEYS)
    return f'{{ subset = "extended", prompts_ref = "{pref}", num_eval_examples = 55, seed = 42{gt_grader}{sk} }}'


def grader_args(pref):
    return GRADER.replace('prompts_ref = "selfplay_oe"', f'prompts_ref = "{pref}"')


for dname, dbody in DEBATERS.items():
    for jname, jbody in JUDGES.items():
        for sname, s in SCHEDULES.items():
            run = f"{dname}__{jname}__{sname}"
            envs = f"""[[orchestrator.train.env]]
id = "gpqa-open-ended-debate"
name = "gpqa-openended-debate-bs512-train"
args = {debate_args(s["pref"], s["sched"])}

[[orchestrator.eval.env]]
id = "gpqa-open-ended-debate"
name = "gpqa-openended-debate-bs512-eval"
num_examples = 55
group_size = {EVAL_GROUP_SIZE}
args = {debate_args(s["pref"], s["sched"])}

[[orchestrator.eval.env]]
id = "hf-singleturn"
name = "gpqa-openended-singleagent-eval"
num_examples = 55
group_size = 4
args = {grader_args(s["pref"])}"""
            cfg = f'''# GENERATED by configs/debate/gen.py — do not edit.
# Source: base + debaters/{dname} + judges/{jname} + schedule:{sname}
output_dir = "outputs/isambard/calibration/debate_{run}"
max_steps = 50
seq_len = 65536

[wandb]
project = "{WANDB_PROJECT}"
name = "{run}"

[slurm]
job_name = "debate-{sname}-50step"
project_dir = "{PROJECT_DIR}"
partition = "workq"
exclude = "nid010193"
account = "brics.a6r"
time = "12:00:00"

{BASE}

{dbody}

{jbody}

{envs}
'''
            (out / f"{run}.toml").write_text(cfg)
            print(f"wrote generated/{run}.toml")
